######################################################
# Licensed Materials - Property of HCL Technologies
# HCL Commerce
# (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: v2
description: HCL Commerce Version 9 Helm Chart
keywords:
  - HCL Commerce V9
name: hcl-commerce
version: 2.1.0
kubeVersion: ">=1.13.0-0"
appVersion: "9.1.4.0"
dependencies:
  - name: elasticsearch
    version: 7.9.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: zookeeper
    version: 5.23.0
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
  - name: redis
    version: 11.3.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
