{{- $cfg_ext := tpl .Values.hclCache.configMap.cache_cfg_ext . | fromYaml}}
{{- if and (.Values.metrics.serviceMonitor.enabled) (.Values.cacheApp.enabled) ($cfg_ext.redis.enabled) }}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.cacheApp.name}}
  {{- if $.Values.metrics.serviceMonitor.namespace }}
  namespace: {{ $.Values.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.cacheApp.name}}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
    {{- range $key, $value := $.Values.metrics.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
  - port: metrics
    interval: {{ $.Values.metrics.serviceMonitor.interval }}
    path: /monitor/metrics
  selector:
    matchLabels:
      component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.cacheApp.name}}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
---
{{- end -}}
{{- end -}}
{{- end -}}