######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
{{- if and (.Values.ingress.enabled) ( .Values.dx.enabled) (eq .Values.common.ingressController "nginx") (eq .Values.common.searchEngine "elastic") }}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) }}
{{- range $envType := $envTypeList -}}
{{- if and (ne $envType "share") (get $.Values.dx.namespace $envType) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}-dx
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: ExternalName
  externalName: ambassador.{{ get $.Values.dx.namespace $envType }}.svc.cluster.local
  ports:
  - port: 443
{{- end }}
{{- end }}
{{- end }}