######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
{{- if and .Values.ingress.enabled (eq .Values.common.ingressController "nginx") -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    kubernetes.io/ingress.class: nginx
    nginx.org/ssl-services: "{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web,{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}tooling-web,{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}store-web,{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}crs-app,{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-app,{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}search-app-master,{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}search-app-repeater,{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}query-app,{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}cache-app"
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
spec:
  tls:
  - hosts:
    - cmc.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    - accelerator.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    - admin.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    - org.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    - store.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    - search.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    {{- if and (eq $envType "live") (eq $.Values.common.searchEngine "solr") }}
    - searchrepeater.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    {{- end }}
    - tsapp.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    {{- if and ($.Values.storeWeb.enabled) (eq $.Values.common.searchEngine "elastic") }}
    - www.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    {{- end }}
    {{- $cfg_ext := tpl $.Values.hclCache.configMap.cache_cfg_ext $ | fromYaml }}
    {{- if and ($.Values.cacheApp.enabled) ($.Values.cacheApp.ingress.enabled) ($cfg_ext.redis.enabled) }}
    - cache.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    {{- end }}
    secretName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}-certificate
  rules:
  - host: cmc.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8000
      - path: /tooling
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}tooling-web
          servicePort: 7443
  - host: accelerator.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8001
  - host: admin.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8002
  - host: org.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8004
  {{- if $.Values.crsApp.enabled }}
  - host: store.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /wcs
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}crs-app
          servicePort: 8443
      - path: /wcsstore
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}crs-app
          servicePort: 8443
      - path: /webapp/remote/preview
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}crs-app
          servicePort: 8443
  {{- else if $.Values.common.localStoreEnabled }}
  - host: store.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 443
  {{- end }}
  {{- if and ($.Values.storeWeb.enabled) (eq $.Values.common.searchEngine "elastic") }}
  - host: www.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}store-web
          servicePort: 6443
      - path: /wcs
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-app
          servicePort: 5443
      - path: /search
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}query-app
          servicePort: 30901
      - path: /lobtools
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8000
      - path: /rest
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8000
      - path: /tooling
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}tooling-web
          servicePort: 7443
  {{- end }}
  {{- if eq $.Values.common.searchEngine "solr" }}
      {{- if eq $envType "auth"}}
  - host: search.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}search-app-master
          servicePort: 3738
      {{- end }}
      {{- if eq $envType "live"}}
  - host: searchrepeater.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}search-app-repeater
          servicePort: 3738
      {{- end }}
  {{- end }}
  {{- if eq $.Values.common.searchEngine "elastic" }}
  - host: search.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}query-app
          servicePort: 30901
  {{- end }}
  - host: tsapp.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-app
          servicePort: 5443
  {{- if and ($.Values.cacheApp.enabled) ($.Values.cacheApp.ingress.enabled) ( $cfg_ext.redis.enabled ) }}
  - host: cache.{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.common.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}cache-app
          servicePort: 40901
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}