######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
{{- if eq .Values.common.searchEngine "elastic" -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" -}}
{{- $_ := set $ "envType" $envType }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.queryApp.name}}
  namespace: {{ $.Release.Namespace }}
spec:
  selector: 
    matchLabels:
      chart: {{ $.Chart.Name }}
      release: {{ $.Release.Name }}
      heritage: {{ $.Release.Service }}
      component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.queryApp.name}}
      group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
  replicas: {{ get $.Values.queryApp.replica $envType }}
  template:
    metadata:
      annotations:
        productName: "HCL Commerce"
        productVersion: {{ $.Values.common.productVersion | quote }}
        deployTime: {{ now }}
      labels:
        app: HCL-Commerce
        chart: {{ $.Chart.Name }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
        component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.queryApp.name}}
        group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
    spec:
      {{- if $.Values.queryApp.nodeSelector }}
      nodeSelector:
{{ get $.Values.queryApp.nodeSelector $envType | toYaml | indent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
           {{- if $.Values.queryApp.nodeLabel }}
           requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: wc-node-select-flag
                  operator: In
                  values: 
                  - {{ $.Values.queryApp.nodeLabel }}
           {{- else }}
           requiredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityRequiredDuringScheduling" $ | indent 8 }}
           {{- end }}   
           preferredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityPreferredDuringScheduling" $ | indent 8 }}
      {{- include "queryapp-podAntiAffinity" $ | indent 6 }}   
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ $.Values.common.serviceAccountName | default (printf "%s-commerce" $.Release.Name) }}
      initContainers:
        - name: query-dependence-check
          image: "{{ include "image.repo" $ }}{{ $.Values.supportC.image }}:{{ $.Values.supportC.tag }}"
          {{- if $.Values.common.imagePullPolicy }}
          imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
          {{- end }}
          args: ['depcheck', '-component','query','-tenant',{{ $.Values.common.tenant }},'-env',{{ $.Values.common.environmentName}},'-envtype',{{ $envType }},'-namespace',{{ $.Release.Namespace }},'-interval_time','20','-expect_during_time','600','-timeout','10','-spiuser_pwd_encrypte',{{ $.Values.common.spiUserPwdBase64 }}]
      volumes:
        - name: logs-sharing
          emptyDir: {}
        - name: cores-sharing
        {{- if get $.Values.queryApp.coresSharingPersistentVolumeClaim $envType }}
          persistentVolumeClaim:
            claimName: {{ get $.Values.queryApp.coresSharingPersistentVolumeClaim $envType }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if $.Values.common.bindingConfigMap }}
        - name: config-volume
          configMap:
            name: {{ $.Values.common.bindingConfigMap }} 
      {{- end }}
      {{- if $.Values.hclCache.configMap }}
        - name: hcl-cache-config
          configMap:
            name: {{ include "hcl.cache.configmap.name" $ | quote }}
      {{- end }}
      {{- if and $.Values.fileBeat.enabled $.Values.queryApp.fileBeatConfigMap }}
        - name: filebeat-config-query-app
          configMap:
            name: {{ $.Values.queryApp.fileBeatConfigMap }}
      {{- end }}
      {{- if include "image.pull.secret" $ }}
      imagePullSecrets:
        - name: {{ include "image.pull.secret" $ }}
      {{- end }}
      containers:
      - name: query-app
        image: "{{ include "image.repo" $ }}{{ $.Values.queryApp.image }}:{{ $.Values.queryApp.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        resources:
{{ get $.Values.queryApp.resources $envType | toYaml | indent 12 }}
        env:
        - name: "LICENSE"
          value: {{ $.Values.license | quote }}
        - name: "CONFIGURE_MODE"
          value: {{ $.Values.common.configureMode | quote }}
        - name: "ENVIRONMENT"
          value: {{ $.Values.common.environmentName | quote }}
        - name: "TENANT"
          value: {{ $.Values.common.tenant | quote }}
        - name: "ENVTYPE"
          value: {{ $envType | quote }}
        - name: "DOMAIN_NAME"
          value: "{{ $.Release.Namespace }}.svc.cluster.local"
        {{- if $.Values.metrics.enabled }}
        - name: "EXPOSE_METRICS"
          value: "true"
        {{- end }}
        - name: "VAULT_CA"
          value: {{ $.Values.vaultCA.enabled | quote }}
        {{- if (or (eq $.Values.common.configureMode "Vault") $.Values.vaultCA.enabled) }}
        - name: "VAULT_URL"
          value: {{ $.Values.common.vaultUrl | quote  }}
        {{- if $.Values.common.vaultTokenSecret }}
        - name: "VAULT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.common.vaultTokenSecret }}
              key: VAULT_TOKEN
        {{- end }}
        {{- end }}       
{{- if get $.Values.queryApp.envParameters $envType }}
     {{- range $key, $value := get $.Values.queryApp.envParameters $envType }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
     {{- end }} 
{{- end }}
        ports: 
        - containerPort: 30900
          name: port30900
          protocol: TCP
        - containerPort: 30901
          name: port30901
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 30901
            scheme: HTTPS
          initialDelaySeconds: 240
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 30901
            scheme: HTTPS
        securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
        volumeMounts:
          - name: logs-sharing
            mountPath: /opt/WebSphere/Liberty/usr/servers/default/logs/container
          - name: cores-sharing
            mountPath: /opt/WebSphere/Liberty/usr/servers/default/cores/container
        {{- if $.Values.common.bindingConfigMap }}
          - name: config-volume
            mountPath: /SETUP/ext-config/config.properties
            subPath: config.properties
            readOnly: false
        {{- end }}
        {{- if $.Values.hclCache.configMap }}
          - name: hcl-cache-config
            mountPath: /SETUP/hcl-cache/cache_cfg-ext.yaml
            subPath: cache_cfg-ext.yaml
          - name: hcl-cache-config
            mountPath: /SETUP/hcl-cache/redis_cfg.yaml
            subPath: redis_cfg.yaml
        {{- end }}
{{- if $.Values.fileBeat.enabled }} 
      - name: filebeat
        image: "{{ include "image.repo" $ }}{{ $.Values.fileBeat.image }}:{{ $.Values.fileBeat.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        resources:
{{ toYaml $.Values.fileBeat.resources | indent 12 }}
        args: ["-indexName", "{{ $.Values.common.tenant }}-{{ $.Values.common.environmentName}}-{{ $envType }}", "-targetELK", "{{ $.Values.fileBeat.elkServer }}", "-componentType", "query-app"]
        securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
        volumeMounts:
        - name: logs-sharing
          mountPath: /log
  {{- if $.Values.queryApp.fileBeatConfigMap }}
        - name: filebeat-config-query-app
          mountPath: /etc/filebeat
  {{- end }}
{{- end }}

{{- end }}
---
{{- end }}
{{- end }}