######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- if and (has "share" $envTypeList) (eq .Values.common.searchEngine "elastic") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.registryApp.name}}
  labels:
    app: HCL-Commerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.registryApp.name}}
    group: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.google.com/app-protocols: '{"port30400":"HTTP"}'
spec:
  type: NodePort
  ports:
  - port: 30400
    name: port30400
  selector:
    component: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.registryApp.name}}
{{- end -}}