######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
{{- if .Values.tsDb.enabled }}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) }}
{{- range $envType := $envTypeList }}
{{- if ne $envType "share" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}db
  namespace: {{ $.Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }} 
spec:
  selector:
    matchLabels:
      component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}db
      group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
      release: {{ $.Release.Name }}
      chart: {{ $.Chart.Name }}
      heritage: {{ $.Release.Service }} 
  replicas: 1
  template:
    metadata:
      annotations:
        productName: "HCL Commerce"
        productVersion: {{ $.Values.common.productVersion | quote }}
      labels:
        component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}db
        group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
        app: HCL-Commerce
        release: {{ $.Release.Name }}
        chart: {{ $.Chart.Name }}
        heritage: {{ $.Release.Service }} 
    spec:
      {{- if $.Values.tsDb.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.tsDb.nodeSelector | indent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
           {{- if $.Values.tsDb.nodeLabel }}
           requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: wc-node-select-flag
                  operator: In
                  values: 
                  - {{ $.Values.tsDb.nodeLabel }}
           {{- else }}
           requiredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityRequiredDuringScheduling" $ | indent 8 }}
           {{- end }}   
           preferredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityPreferredDuringScheduling" $ | indent 8 }}
      hostNetwork: false
      hostPID: false
      hostIPC: false 
      serviceAccountName: {{ $.Values.common.serviceAccountName | default (printf "%s-commerce" $.Release.Name) }}
      {{- if include "image.pull.secret" $ }}
      imagePullSecrets:
        - name: {{ include "image.pull.secret" $ }}
      {{- end }}
      containers:
      - name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}db
        image: {{ include "image.repo" $ }}{{ $.Values.tsDb.image }}:{{ $.Values.tsDb.tag }}
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        resources:
        resources:
{{ toYaml $.Values.tsDb.resources | indent 12 }}
        env:
        - name: "LICENSE"
          value: {{ $.Values.license | quote }}
        securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
              - SYS_RESOURCE
              - IPC_OWNER
              - SYS_NICE
        ports:
        - containerPort: 50000
          name: db
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 50000
          initialDelaySeconds: 600
          timeoutSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 50000
{{- end }}
---
{{- end }}
{{- end }}
