
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{ if and (has "auth" $envTypeList) (eq .Values.common.searchEngine "solr") (.Values.searchAppMaster.persistence.enabled) (not .Values.searchAppMaster.persistence.existingClaim) (not .Values.searchAppMaster.persistentVolumeClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.common.tenant }}{{ .Values.common.environmentName}}-search-master-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
spec:
  accessModes:
  - {{ .Values.searchAppMaster.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.searchAppMaster.persistence.storage }}
  {{- if .Values.searchAppMaster.persistence.storageClass }}
  storageClassName: {{ .Values.searchAppMaster.persistence.storageClass }}
  {{- end }}
{{- end }}