apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-commerce
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
  labels:
    app.kubernetes.io/name: HCL-Commerce
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" | replace "+" "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}