######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
{{- if and (eq .Values.common.searchEngine "elastic") (.Values.storeWeb.enabled) -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{ $.Values.storeWeb.name }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.storeWeb.name}}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    cloud.google.com/app-protocols: '{"port6443":"HTTPS"}'
spec:
  type: NodePort
  ports:
  - port: 6443
    name: port6443
  selector:
    component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.storeWeb.name }}
{{- end }}
---
{{- end }}
{{- end }}